#!/bin/bash
asennushakemisto="/tmp/dvbsub2srtasennus"
sudo apt install -y python3-pyqt5 jq pkg-config xterm tesseract-ocr-swe tesseract-ocr-fin python3-pip git build-essential git automake cmake libcurl4-gnutls-dev tesseract-ocr libtesseract-dev libleptonica-dev imagemagick ogmrip lsdvd mencoder mediainfo ffmpeg
omaSijainti=$(pwd)
rm -rf $asennushakemisto
mkdir -p $asennushakemisto
cd $asennushakemisto
touch $asennushakemisto/loki 2>/dev/null
if [[ $? != "0" ]];then
    echo "Tarkista $asennushakemisto käyttöoikeus. Seis."
    exit
fi

# ***** ASENNETAAN CCEXTRACTOR *****
git clone https://github.com/CCExtractor/ccextractor.git
cd ccextractor/linux
./autogen.sh && ./configure && make && sudo make install

echo "Valmis."
exit 0
